server:
  port: ${PORT:8080}

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: false
    show-sql: false
    open-in-view: false
  datasource:
    hikari:
      connectionTimeout: '30000'
      maximum-pool-size: '8'
      max-lifetime: '1800000'
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    url: jdbc:${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    org:
      apache:
        coyote:
          http11: info
  file:
    name: classpath:/kuring.log

sentry:
  traces-sample-rate: '1.0'
  dsn: ${SENTRY_URL}
