server:
  deploy:
    environment: ${DEPLOY_ENV}
  port: ${PORT:8080}
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        format_sql: true
    defer-datasource-initialization: false
    show-sql: false
    open-in-view: false
  datasource:
    hikari:
      connectionTimeout: '30000'
      maximum-pool-size: '8'
      max-lifetime: '1800000'
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    url: jdbc:${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

decorator:
  datasource:
    p6spy:
      enable-logging: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expire-length: ${JWT_EXPIRE_LENGTH}


notice:
  kuis:
    request-url: https://kuis.konkuk.ac.kr/CmmnOneStop/find.do
    referer-url: https://kuis.konkuk.ac.kr/index.do
  homepage:
    list-url: https://www.konkuk.ac.kr/bbs/{category}/{siteId}/artclList.do
    view-url: https://www.konkuk.ac.kr/bbs/{category}/{siteId}/{noticeId}/artclView.do
  real-estate:
    list-url: http://www.realestate.ac.kr/gb/bbs/board.php?bo_table=notice
    view-url: http://www.realestate.ac.kr/gb/bbs/board.php?bo_table=notice
  recent:
    list-url: https://{department}.konkuk.ac.kr/bbs/{department}/{siteId}/artclList.do
    view-url: https://{department}.konkuk.ac.kr/bbs/{department}/{siteId}/{noticeId}/artclView.do
  normal-base-url: https://old.konkuk.ac.kr/do/MessageBoard/ArticleRead.do
  library:
    request-url: https://library.konkuk.ac.kr/pyxis-api/1/bulletin-boards/1/bulletins
  library-base-url: https://library.konkuk.ac.kr/library-guide/bulletins/notice

auth:
  api-skeleton-producer-url: https://kuis.konkuk.ac.kr/ui/cpr-lib/user-modules.js?p=0.9460032500983822
  password: ${KU_PASSWORD}
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36 Edg/94.0.992.38
  id: ${KU_ID}
  session: JSESSIONID=00015GJS2T_gl7M-TqGjYvyHAuJ:-103KQM
  referer: https://kuis.konkuk.ac.kr/index.do
  login-url: https://kuis.konkuk.ac.kr/Login/login.do

firebase:
  file-path: third/ku-stack-firebase-adminsdk-87nwq-5ba04dfc12.json

admin:
  password: ${ADMIN_PASSWORD}
  id: ${ADMIN_ID}

ip:
  proxy-list: 14.63.228.239:80, 101.79.15.198:80, 222.104.128.205:8678, 106.244.154.91:8080, 103.51.205.42:8181

staff:
  real-estate-url: http://www.realestate.ac.kr/gb/bbs/board.php?bo_table=faculty
  communication-design-url: http://www.konkuk.ac.kr/jsp/Coll/coll_01_13_01_01_tab01.jsp
  living-design-url: http://www.konkuk.ac.kr/jsp/Coll/coll_01_13_01_05_tab01.jsp
  each-dept-url: http://home.konkuk.ac.kr/cms/Common/Professor/ProfessorList.do
